// Generated by retool-db-types

export interface __retool_vector_bad_coffee_shops_06f52c66_0142_482c_bea1_fa8270 {
  id: number
  embedding: unknown | null
  content: string | null
  source: string | null
}

export interface __retool_vector_top_coffee_shops_dfe6ef85_d189_4706_8d7f_ea6c70 {
  id: number
  embedding: unknown | null
  content: string | null
  source: string | null
}

export interface Coffee_db {
  alias: string
  aiScore: number | null
  aiNotes: string | null
  id: string
  name: string
  image_url: string | null
  is_closed: boolean | null
  url: string | null
  review_count: number | null
  title: string | null
}

export interface Coffee_app_dev {
  id: string
  audience: string | null
  confirmation_sent_at: unknown | null
  confirmed_at: unknown | null
  created_at: unknown | null
  email: string | null
  role: string | null
  updated_at: unknown | null
  url: string | null
  user_metadata: Record<string, unknown> | null
}
